# Generated by Django 3.0.6 on 2020-05-23 12:35

import api.models.users
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=78)),
                ('password_hash', models.CharField(editable=False, max_length=78, null=True)),
                ('token', models.CharField(editable=False, max_length=48, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ('joined',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=4096)),
                ('author', models.ForeignKey(on_delete=models.SET(api.models.users.DeletedUser), related_name='posts', to='api.User')),
                ('likes', models.ManyToManyField(related_name='posts_liked', to='api.User')),
                ('visits', models.ManyToManyField(related_name='posts_visited', to='api.User')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=512)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Post')),
                ('user', models.ForeignKey(on_delete=models.SET(api.models.users.DeletedUser), related_name='comments', to='api.User')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('created',),
            },
        ),
    ]
